### ISSUE TITLE
Missing licence

### ISSUE THREAD

**Issue by yochannah** [ewancarr/NEWS2-COVID-19#4]
Hey folks,

Kudos again on a really well documented repo. I just noticed there is [no licence](https://choosealicense.com/no-permission/) that permits re-use of this work - is this something you'd consider adding? The [community panel](https://github.com/ewancarr/NEWS2-COVID-19/community) in Github makes it quite straightforward to add one.

**Comment by yochannah** [comment]
Whatever makes you happiest! MIT is practical because industry is more likely to use it but really either is good. 

[Choosealicence](https://choosealicense.com/) can help with choice too.

**Comment by ewancarr** [comment]
OK great, MIT it is. Thanks again!
